module.exports = {
  CONVERSATION_STATUS: {
    DONE: 'DONE',
    CANCELD: 'CANCELD',
    WAITING: 'WAITING',
    CALLING: 'CALLING',
    UNKNOW: 'UNKNOW'
  },
  USER_STATUS: {
    AVAILABLE: 'AVAILABLE',
    CONNECTING: 'CONNECTING',
    CALLING: 'CALLING',
    UNAVAILABLE: 'UNAVAILABLE'
  }
}
